### ISSUE TITLE
Upgrade to next Java LTS version

### ISSUE THREAD

**Issue by nickmcdowall** [lsd-consulting/lsd-core#56]
Java 17 is the new LTS version so probably worth thinking about updating in the near future.

**Comment by lukasz-gryzbon** [comment]
Hey Nick. Can you share the reasoning behind selecting Handlebars? Pros and cos against alternatives?

**Comment by nickmcdowall** [comment]
Hey,

I had a look around at some of the options and comparisons e.g. 

https://java.libhunt.com/categories/447-template-engine

and handlebars seems to be one of the most popular and well maintained while also not being too dissimilar to what was already use. (Thymeleaf seemed to have good scores but was quite a shift in styles). 

I also tested out switching a couple of the templates in `lsd-core` and the changes to switch were pretty straightforward. The other key thing is I've seen it work with Java 17 in another project.

Saying that I'm open to suggestions if you think there is a better option?

**Comment by lukasz-gryzbon** [comment]
Thanks Nick! I appreciate the response. 

Yes, let's give Handlebars a go 👍
